[package]
name = "swua"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
colored = "2.0.4"
guess_host_triple = "0.1.3"
inkwell = { version = "0.4.0", features = ["llvm17-0"] }
